# This file was auto-generated by Polybuild

include_path_flag := -I
library_path_flag := -L
obj_path_flag := -o
out_path_flag := -o
library_flag := -l
release_dynamic_flag :=
release_static_flag := -static
debug_dynamic_flag :=
debug_static_flag := -static
debug_compilation_flag := -g
debug_link_flag :=
shared_flag := -shared -fPIC
compile_only_flag := -c
link_flag :=
pkg_config_syntax :=
obj_ext := .o
out_ext :=
ifeq ($(OS),Windows_NT)
	include_path_flag := /I
	library_path_flag := /LIBPATH:
	obj_path_flag := /Fo:
	out_path_flag := /Fe:
	library_flag :=
	release_dynamic_flag := /MD
	release_static_flag := /MT
	debug_dynamic_flag := /MDd
	debug_static_flag := /MTd
	debug_compilation_flag := /Zi
	debug_link_flag := /DEBUG
	shared_flag := /LD
	compile_only_flag := /c
	link_flag := /link
	pkg_config_syntax := --msvc-syntax
	obj_ext := .obj
	out_ext := .exe
endif

active_dynamic_flag := $(release_dynamic_flag)
active_static_flag := $(release_static_flag)
active_debug_compilation_flag :=
active_debug_link_flag :=
ifeq ($(MODE),debug)
	active_debug_compilation_flag := $(debug_compilation_flag)
	active_debug_link_flag := $(debug_link_flag)
	active_dynamic_flag := $(debug_dynamic_flag)
	active_static_flag := $(debug_static_flag)
endif

c_compiler := "$(CC)"
cpp_compiler := "$(CXX)"
c_compilation_flags := $(CFLAGS) $(active_debug_compilation_flag) $(include_path_flag)fltk $(active_dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags gio-2.0`
cpp_compilation_flags := -Wall -Wno-unused-result -std=c++23 -Ifltk/build -O3 $(active_debug_compilation_flag) $(include_path_flag)fltk $(active_dynamic_flag) `pkg-config $(pkg_config_syntax) --cflags gio-2.0`
link_time_flags := `fltk/build/fltk-config --ldstaticflags` $(active_debug_link_flag)
libraries := $(library_flag)"ssl" $(library_flag)"crypto" `pkg-config $(pkg_config_syntax) --libs "gio-2.0"`
prefix := "/usr/local/bin"

ifeq ($(OS),Windows_NT)
	c_compiler := "$(CC)"
	cpp_compiler := "$(CXX)"
	c_compilation_flags := $(CFLAGS) $(active_debug_compilation_flag) $(include_path_flag)fltk $(active_static_flag)
	cpp_compilation_flags := /W3 /std:c++latest /EHsc /DWIN32_LEAN_AND_MEAN /DNOMINMAX /I"fltk" /I"fltk/build" /I"$(OPENSSL_ROOT_DIR)"/include /O2 $(active_debug_compilation_flag) $(include_path_flag)fltk $(active_static_flag)
	link_time_flags := /SUBSYSTEM:WINDOWS $(library_path_flag)"\"$(OPENSSL_ROOT_DIR)\"/lib"
	libraries := $(library_flag)"libssl.lib" $(library_flag)"libcrypto.lib" $(library_flag)"ws2_32.lib" $(library_flag)"crypt32.lib" $(library_flag)"advapi32.lib" $(library_flag)"shell32.lib" $(library_flag)"dwmapi.lib" $(library_flag)"gdiplus.lib" $(library_flag)"ole32.lib" $(library_flag)"comdlg32.lib" $(library_flag)"winspool.lib" $(library_flag)"user32.lib" $(library_flag)"kernel32.lib" $(library_flag)"gdi32.lib" $(library_flag)"comctl32.lib"
	static_libraries := fltk/build/lib/fltk.lib
	prefix := "C:\\tenebra-gtk\\bin"
endif

all: tenebra-gtk$(out_ext)
.PHONY: all

obj/main_0$(obj_ext): ./main.cpp .polybuild.mk ./Polyweb/polyweb.hpp ./Polyweb/Polynet/polynet.hpp ./Polyweb/Polynet/error.hpp ./Polyweb/Polynet/string.hpp ./Polyweb/Polynet/tls.hpp ./Polyweb/error.hpp ./Polyweb/string.hpp ./Polyweb/thread_pool.hpp ./json.hpp ./theme.hpp ./toml.hpp ./toml/parser.hpp ./toml/combinator.hpp ./toml/region.hpp ./toml/color.hpp ./toml/result.hpp ./toml/traits.hpp ./toml/from.hpp ./toml/into.hpp ./toml/version.hpp ./toml/utility.hpp ./toml/lexer.hpp ./toml/macros.hpp ./toml/types.hpp ./toml/comments.hpp ./toml/datetime.hpp ./toml/string.hpp ./toml/value.hpp ./toml/exception.hpp ./toml/source_location.hpp ./toml/storage.hpp ./toml/literal.hpp ./toml/serializer.hpp ./toml/get.hpp ./util.hpp fltk/FL/Fl.H fltk/FL/Fl_Export.H fltk/FL/platform_types.h fltk/FL/fl_casts.H fltk/FL/Fl_Cairo.H fltk/FL/fl_utf8.h fltk/FL/fl_types.h fltk/FL/fl_attr.h fltk/FL/Enumerations.H fltk/FL/Fl_Box.H fltk/FL/Fl_Widget.H fltk/FL/Fl_Button.H fltk/FL/Fl_Check_Button.H fltk/FL/Fl_Light_Button.H fltk/FL/Fl_Choice.H fltk/FL/Fl_Menu_.H fltk/FL/Fl_Menu_Item.H fltk/FL/Fl_Image.H fltk/FL/Fl_Multi_Label.H fltk/FL/Fl_Window.H fltk/FL/Fl_Group.H fltk/FL/Fl_Bitmap.H fltk/FL/Fl_Double_Window.H fltk/FL/Fl_File_Chooser.H fltk/FL/Fl_Menu_Button.H fltk/FL/Fl_Preferences.H fltk/FL/Fl_Tile.H fltk/FL/Fl_File_Browser.H fltk/FL/Fl_Browser.H fltk/FL/Fl_Browser_.H fltk/FL/Fl_Scrollbar.H fltk/FL/Fl_Slider.H fltk/FL/Fl_Valuator.H fltk/FL/Fl_File_Icon.H fltk/FL/filename.H fltk/FL/Fl_File_Input.H fltk/FL/Fl_Input.H fltk/FL/Fl_Input_.H fltk/FL/Fl_Return_Button.H fltk/FL/fl_ask.H fltk/FL/Fl_Flex.H fltk/FL/Fl_Hor_Slider.H fltk/FL/Fl_Scroll.H fltk/FL/Fl_Secret_Input.H fltk/FL/Fl_Spinner.H fltk/FL/Fl_Repeat_Button.H fltk/FL/fl_callback_macros.H fltk/FL/fl_draw.H fltk/FL/Fl_Graphics_Driver.H fltk/FL/Fl_Device.H fltk/FL/Fl_Plugin.H fltk/FL/Fl_Pixmap.H fltk/FL/Fl_RGB_Image.H fltk/FL/Fl_Rect.H fltk/FL/platform.H fltk/FL/win32.H fltk/FL/wayland.H fltk/FL/x11.H fltk/FL/mac.H
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/theme_0$(obj_ext): ./theme.cpp .polybuild.mk ./theme.hpp fltk/FL/Fl.H fltk/FL/Fl_Export.H fltk/FL/platform_types.h fltk/FL/fl_casts.H fltk/FL/Fl_Cairo.H fltk/FL/fl_utf8.h fltk/FL/fl_types.h fltk/FL/fl_attr.h fltk/FL/Enumerations.H fltk/FL/fl_draw.H fltk/FL/Fl_Graphics_Driver.H fltk/FL/Fl_Device.H fltk/FL/Fl_Plugin.H fltk/FL/Fl_Preferences.H fltk/FL/Fl_Image.H fltk/FL/Fl_Widget.H fltk/FL/Fl_Bitmap.H fltk/FL/Fl_Pixmap.H fltk/FL/Fl_RGB_Image.H fltk/FL/Fl_Rect.H
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/util_0$(obj_ext): ./util.cpp .polybuild.mk ./util.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/client_0$(obj_ext): Polyweb/client.cpp .polybuild.mk Polyweb/polyweb.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/tls.hpp Polyweb/error.hpp Polyweb/string.hpp Polyweb/thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/error_0$(obj_ext): Polyweb/error.cpp .polybuild.mk Polyweb/error.hpp Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/polyweb_0$(obj_ext): Polyweb/polyweb.cpp .polybuild.mk Polyweb/polyweb.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/tls.hpp Polyweb/error.hpp Polyweb/string.hpp Polyweb/thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/server_0$(obj_ext): Polyweb/server.cpp .polybuild.mk Polyweb/polyweb.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/tls.hpp Polyweb/error.hpp Polyweb/string.hpp Polyweb/thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/string_0$(obj_ext): Polyweb/string.cpp .polybuild.mk Polyweb/string.hpp Polyweb/Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/websocket_0$(obj_ext): Polyweb/websocket.cpp .polybuild.mk Polyweb/binary.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp Polyweb/polyweb.hpp Polyweb/Polynet/tls.hpp Polyweb/error.hpp Polyweb/string.hpp Polyweb/thread_pool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/error_1$(obj_ext): Polyweb/Polynet/error.cpp .polybuild.mk Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/polynet_0$(obj_ext): Polyweb/Polynet/polynet.cpp .polybuild.mk Polyweb/Polynet/polynet.hpp Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/tls_0$(obj_ext): Polyweb/Polynet/tls.cpp .polybuild.mk Polyweb/Polynet/tls.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/error.hpp Polyweb/Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(cpp_compiler) $(compile_only_flag) $< $(cpp_compilation_flags) $(obj_path_flag)$@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

objects :=  obj/main_0$(obj_ext) obj/theme_0$(obj_ext) obj/util_0$(obj_ext) obj/client_0$(obj_ext) obj/error_0$(obj_ext) obj/polyweb_0$(obj_ext) obj/server_0$(obj_ext) obj/string_0$(obj_ext) obj/websocket_0$(obj_ext) obj/error_1$(obj_ext) obj/polynet_0$(obj_ext) obj/tls_0$(obj_ext)
tenebra-gtk$(out_ext): .polybuild.mk $(objects) $(static_libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Building $@..."
	@$(cpp_compiler) $(objects) $(static_libraries) $(cpp_compilation_flags) $(out_path_flag)$@ $(link_flag) $(link_time_flags) $(libraries)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished building $@!"

clean:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Executing clean prelude: rm -rf fltk/build"
	@rm -rf fltk/build
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Deleting tenebra-gtk$(out_ext) and obj..."
	@rm -rf tenebra-gtk$(out_ext) obj
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished deleting tenebra-gtk$(out_ext) and obj!"
.PHONY: clean

install:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Copying tenebra-gtk$(out_ext) to $(prefix)..."
	@cp tenebra-gtk$(out_ext) $(prefix)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished copying tenebra-gtk$(out_ext) to $(prefix)!"
.PHONY: install
