# This file was auto-generated by Polybuild

ifndef OS
	OS := $(shell uname)
endif

obj_ext := .o
ifeq ($(OS),Windows_NT)
	obj_ext := .obj
	out_ext := .exe
endif

compiler := $(CXX)
compilation_flags := -Wall -Wno-unused-result -std=c++17 -O3 `pkg-config --cflags libadwaita-1 gtk4`
link_time_flags := $(LDFLAGS)
libraries := -lssl -lcrypto `pkg-config --libs libadwaita-1 gtk4`

all: tenebra-gtk$(out_ext)
.PHONY: default

obj/main_0$(obj_ext): ./main.cpp ./Polyweb/polyweb.hpp ./Polyweb/Polynet/polynet.hpp ./Polyweb/Polynet/string.hpp ./Polyweb/Polynet/secure_sockets.hpp ./Polyweb/Polynet/smart_sockets.hpp ./Polyweb/string.hpp ./Polyweb/threadpool.hpp ./glib.hpp ./json.hpp ./toml.hpp ./toml/parser.hpp ./toml/combinator.hpp ./toml/region.hpp ./toml/color.hpp ./toml/result.hpp ./toml/traits.hpp ./toml/from.hpp ./toml/into.hpp ./toml/version.hpp ./toml/utility.hpp ./toml/lexer.hpp ./toml/macros.hpp ./toml/types.hpp ./toml/comments.hpp ./toml/datetime.hpp ./toml/string.hpp ./toml/value.hpp ./toml/exception.hpp ./toml/source_location.hpp ./toml/storage.hpp ./toml/literal.hpp ./toml/serializer.hpp ./toml/get.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/string_0$(obj_ext): Polyweb/string.cpp Polyweb/string.hpp Polyweb/Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/client_0$(obj_ext): Polyweb/client.cpp Polyweb/polyweb.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/secure_sockets.hpp Polyweb/Polynet/smart_sockets.hpp Polyweb/string.hpp Polyweb/threadpool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/polyweb_0$(obj_ext): Polyweb/polyweb.cpp Polyweb/polyweb.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/secure_sockets.hpp Polyweb/Polynet/smart_sockets.hpp Polyweb/string.hpp Polyweb/threadpool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/websocket_0$(obj_ext): Polyweb/websocket.cpp Polyweb/polyweb.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/secure_sockets.hpp Polyweb/Polynet/smart_sockets.hpp Polyweb/string.hpp Polyweb/threadpool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/server_0$(obj_ext): Polyweb/server.cpp Polyweb/polyweb.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/secure_sockets.hpp Polyweb/Polynet/smart_sockets.hpp Polyweb/string.hpp Polyweb/threadpool.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/polynet_0$(obj_ext): Polyweb/Polynet/polynet.cpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/string.hpp Polyweb/Polynet/secure_sockets.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

obj/secure_sockets_0$(obj_ext): Polyweb/Polynet/secure_sockets.cpp Polyweb/Polynet/secure_sockets.hpp Polyweb/Polynet/polynet.hpp Polyweb/Polynet/string.hpp
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Compiling $@ from $<..."
	@mkdir -p obj
	@$(compiler) -c $< $(compilation_flags) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished compiling $@ from $<!"

tenebra-gtk$(out_ext): obj/main_0$(obj_ext) obj/string_0$(obj_ext) obj/client_0$(obj_ext) obj/polyweb_0$(obj_ext) obj/websocket_0$(obj_ext) obj/server_0$(obj_ext) obj/polynet_0$(obj_ext) obj/secure_sockets_0$(obj_ext)
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Building $@..."
	@$(compiler) $^ $(static_libraries) $(compilation_flags) $(link_time_flags) $(libraries) -o $@
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished building $@!"

clean:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Deleting tenebra-gtk$(out_ext) and obj..."
	@rm -rf tenebra-gtk$(out_ext) obj
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished deleting tenebra-gtk$(out_ext) and obj!"
.PHONY: clean

install:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Copying tenebra-gtk$(out_ext) to /usr/local/bin..."
	@cp tenebra-gtk$(out_ext) /usr/local/bin
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Finished copying tenebra-gtk to /usr/local/bin!"
.PHONY: install
