[package]
name = "tenebra-gtk"
# (Optional) Descriptive text about your package; some installers will present this to users
description = "A GTK 4 frontend for Tenebra built with libadwaita."
version = "0.1.3"
license = "GPL-3.0-only"
repository = "https://github.com/BlueCannonBall/tenebra-gtk"
binaries = ["tenebra-gtk"]
build-command = ["make"]

[dist.dependencies.apt]
libgtk-4-dev = "*"
libadwaita-1-dev = "*"
