[workspace]
members = ["dist:."]

[package]
name = "tenebra-gtk"
# (Optional) Descriptive text about your package; some installers will present this to users
description = "A GTK 4 frontend for Tenebra built with libadwaita."
version = "0.9.0"
license = "GPL-3.0-only"
repository = "https://github.com/BlueCannonBall/tenebra-gtk"
binaries = ["tenebra-gtk"]
build-command = ["make"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

[dist.dependencies.apt]
libgtk-4-dev = "*"
libadwaita-1-dev = "*"
libssl-dev = "*"

[dist.github-custom-runners]
global = "ubuntu-latest"

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-latest"
