# This file was auto-generated by Polybuild

ifndef MODE
	MODE := release
	export MODE
endif

ifndef OS
	OS := $(shell uname)
	export OS
endif

ifeq ($(OS),Windows_NT)
	CC := cl
	CXX := cl
	CL := /nologo
	LINK := /nologo
	MSYS_NO_PATHCONV := 1
	export CC CXX CL MSYS_NO_PATHCONV
endif

all: prelude0
	@"$(MAKE)" -f .polybuild.mk --no-print-directory
.PHONY: all

prelude0:
	@printf "\033[1m[POLYBUILD]\033[0m %s\n" "Executing prelude:  cd fltk && cmake . -B build -G \"Unix Makefiles\" -DCMAKE_BUILD_TYPE=Release -DFLTK_BACKEND_WAYLAND=OFF -DFLTK_BUILD_TEST=OFF -DFLTK_BUILD_FLUID=OFF -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_MSVC_RUNTIME_DLL=OFF && \"$(MAKE)\" -C build "
	@ cd fltk && cmake . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLTK_BACKEND_WAYLAND=OFF -DFLTK_BUILD_TEST=OFF -DFLTK_BUILD_FLUID=OFF -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_MSVC_RUNTIME_DLL=OFF && "$(MAKE)" -C build 
.PHONY: prelude0

clean:
	@"$(MAKE)" -f .polybuild.mk --no-print-directory $@
.PHONY: clean

install:
	@"$(MAKE)" -f .polybuild.mk --no-print-directory $@
.PHONY: install
