# This file was auto-generated by Polybuild

all:
	@$(MAKE) -f .polybuild.mk --no-print-directory
.PHONY: all

clean:
	@$(MAKE) -f .polybuild.mk --no-print-directory $@
.PHONY: clean

install:
	@$(MAKE) -f .polybuild.mk --no-print-directory $@
.PHONY: install
